# Generated by Django 5.1.7 on 2025-03-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='weight',
        ),
    ]
