# Generated by Django 5.1.7 on 2025-03-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='given_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
