# Generated by Django 5.1.7 on 2025-04-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_given_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.CharField(choices=[('required check', 'Required check'), ('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='nlp_metadata',
            field=models.JSONField(blank=True, help_text='Сохраненные результаты NLP анализа (ключевые слова, срочность и т.д.)\n        Метаданные NLP-обработки описания задачи. Содержит:\n        - извлеченные ключевые слова\n        - распознанные даты/дедлайны\n        - оценку срочности\n        - другие параметры для автоматического управления задачами\n        ', null=True),
        ),
    ]
