# Generated by Django 5.1.7 on 2025-04-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_taskcategory_options_taskcategory_auto_assign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
