# Generated by Django 5.1.7 on 2025-04-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_taskcategory_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='taskcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taskcategory',
            name='keywords_vector',
        ),
        migrations.RemoveField(
            model_name='taskcategory',
            name='nlp_metadata',
        ),
        migrations.RemoveField(
            model_name='taskcategory',
            name='task_count',
        ),
        migrations.RemoveField(
            model_name='taskcategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='taskcategory',
            name='weight',
        ),
        migrations.AddField(
            model_name='task',
            name='predicted_duration',
            field=models.FloatField(blank=True, help_text='Предсказанное время выполнения в часах', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='nlp_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Сохраненные результаты NLP анализа (ключевые слова, срочность и т.д.)\n        Метаданные NLP-обработки описания задачи. Содержит:\n        - извлеченные ключевые слова\n        - распознанные даты/дедлайны\n        - оценку срочности\n        - другие параметры для автоматического управления задачами\n        ', null=True),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='auto_assign',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='min_confidence',
            field=models.FloatField(default=0.7),
        ),
    ]
