# Generated by Django 4.2.20 on 2025-04-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_taskcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='processed_keywords',
            field=models.TextField(blank=True, editable=False, help_text='Автоматически обработанные ключевые слова'),
        ),
        migrations.AlterField(
            model_name='task',
            name='nlp_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Сохраненные результаты NLP анализа (ключевые слова, срочность и т.д.)', null=True),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='keywords',
            field=models.TextField(blank=True, help_text='Список ключевых слов через запятую'),
        ),
    ]
