# Generated by Django 4.2.20 on 2025-04-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_taskcategory_processed_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
