# Generated by Django 4.2.20 on 2025-04-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_taskcategory_processed_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('task_number',), name='unique_project_task_number'),
        ),
    ]
