# Generated by Django 4.2.20 on 2025-04-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_task_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
