# Generated by Django 4.2.20 on 2025-05-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_sprint_name_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategory',
            name='auto_assign',
        ),
        migrations.RemoveField(
            model_name='taskcategory',
            name='min_confidence',
        ),
    ]
